In [1]:
import urllib.request
from bs4 import BeautifulSoup as soup
import requests
import re
import pandas as pd
link = 'https://rally-base.com/2023/rally-sweden-2023/?ssId='
startat, no_ss=7337, int(11)
sweden_23 = []

In [2]:
for ss in range(0,(no_ss)):
    val= startat + ss
    ss_a = str(val)
    my_url11 = link + ss_a
    #print(ss, val, ss_a, "\n", my_url11)
    
    req = urllib.request.Request(my_url11, headers={'User-Agent': 'Mozilla/5.0'})
    uClient11 = urllib.request.urlopen(req)
    page_html11 = uClient11.read()
    uClient11.close()
    data = pd.read_html(page_html11)[1]
        
    data.columns = data.iloc[0]
    data = data[1:]
    data['ss']=ss+1
    #print(data.columns)
    
    equal = '-' in data['Pos.'].unique()
    if equal:
        data['Pos.'] = data['Pos.'].replace('-', method='ffill')
    
    data.to_csv('02_sweden23_SS'+str(ss+1)+'.csv', index=False)

    sweden_23.append(data)

In [4]:
sweden2023_stages = pd.concat(sweden_23, axis=0)
sweden2023_stages['Pos.'] = sweden2023_stages['Pos.'].astype(str).astype(int)
sweden2023_stages['No.'] = sweden2023_stages['No.'].astype(str).astype(int)
sweden2023_stages.info()
sweden2023_stages.to_csv('02_sweden2023.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 561 entries, 1 to 51
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pos.                        561 non-null    int32
 1   No.                         561 non-null    int32
 2   Driver / Co-driver Vehicle  561 non-null    object
 3   Group                       561 non-null    object
 4   SS time                     561 non-null    object
 5   Aver. speed sec/km          561 non-null    object
 6   Diff.Leader Diff.Prev.      561 non-null    object
 7   ss                          561 non-null    int64
dtypes: int32(2), int64(1), object(5)
memory usage: 35.1+ KB

In [9]:
sweden2023_temp=sweden2023_stages.drop(['Group','SS time', 'Aver. speed sec/km', 'Diff.Leader Diff.Prev.'], axis=1)
sweden2023_view = sweden2023_temp.set_index(['No.','Driver / Co-driver Vehicle','ss'], drop=True).unstack('ss')
sweden2023_view

0                                                      Pos.                  \
ss                                                       1   2   3   4   5
No. Driver / Co-driver Vehicle
4   Lappi  Esapekka  /  Ferm  Janne  Hyundai i20 N ...    4   3   2   5   3
7   Loubet  P.  /  Gilsoul  Nicolas  Ford Puma Rall...    8   7   8   8   2
8   Tänak  Ott  /  Järveoja  M.  Ford Puma Rally1 H...    2   2   4   3   4
11  Neuville  T.  /  Wydaeghe  M.  Hyundai i20 N Ra...    5   5   6   7   6
18  Katsuta  T.  /  Johnston  Aaron  Toyota GR Yari...    6   4   3   1  21
20  Solberg  Oliver  /  Edmondson  E.  Škoda Fabia ...   11  13   9  11   7
21  Veiby  O.  /  Eriksen  T.  Volkswagen Polo Gti R5    10  14  11  17  19
22  Lindholm  Emil  /  Hämäläinen  R.  Škoda Fabia ...   12   9  48  16   8
23  Suninen  Teemu  /  Markkula  Mikko  Hyundai i20...   14  10  13  13  45
24  Huttunen  Jari  /  Linnaketo  Antti  Škoda Fabi...    9  12  15  15  13
25  Linnamäe  Georg  /  Morgan  James  Hyundai i20 ...   22  21  20  19  17
26  Kaur  Egon  /  Viilo  Jakko  Škoda Fabia Rally2...   20  17  17  12  34
27  Gryazin  Nikolay  /  Aleksandrov  K.  Škoda Fab...   15  18  12  14  14
28  Pajari  Sami  /  Mälkönen  Enni  Škoda Fabia RS...   12  11  16  10  12
29  Virves  Robert  /  Magalhães  Hugo  Ford Fiesta...   23  20  21  20  11
30  Joona  Lauri  /  Shemeikka  T.  Škoda Fabia Ral...   19  22  18  21  16
31  Bulacia  Marco  /  Vallejo  Diego  Škoda Fabia ...   16  16  14  18  33
32  Bulacia  Bruno  /  Coronado  Axel  Škoda Fabia ...   16  23  22  22  15
33  Evans  Elfyn  /  Martin  Scott  Toyota GR Yaris...    3   6   7   6   5
34  Zaldivar  F.  /  Der Ohannesian  M.  Hyundai i2...   21  19  19  23  18
35  Al-Rashed  Rakan  /  Moscatt  Dale  Škoda Fabia...   30  29  33  32  20
36  Sołowow  M.  /  Baran  Maciej  Škoda Fabia RS R...   27  25  24  24  22
37  Bertelli  L.  /  Scattolin  S.  Toyota GR Yaris...   18  15  10   9  10
38  Miele  Mauro  /  Beltrame  Luca  Škoda Fabia Ra...   32  36  35  38  28
40  Alonso  Daniel  /  Lopez  Alejandro  Citroën C3...   38  37  36  37  31
41  Jonasson  J.  /  Jonasson  N.  Škoda Fabia Rall...   24  24  23  26  23
42  Breen  Craig  /  Fulton  James  Hyundai i20 N R...    7   1   5   4   1
44  Cobbe  Luciano  /  Mometti  Roberto  Škoda Fabi...   45  51  47  49  44
45  Roman  Joakim  /  Lidebjer Granberg  I.  Škoda ...   40  47  38  39  38
46  Zaldivar  Miguel  /  Díaz  J.  Hyundai i20 N Ra...   37  32  32  35  30
47  Díaz Aboitiz  M.  /  Del Barrio  R.  Škoda Fabi...   45  49  45  47  41
48  Villanueva  A.  /  Murado  José  Škoda Fabia Ra...   42  35  29  30  48
49  Korhonen  Roope  /  Viinikka  Anssi  Ford Fiest...   26  27  25  25  26
50  Creighton  W.  /  Regan  Liam  Ford Fiesta Rally3    25  26  26  27  27
51  Munster  G.  /  Louka  Louis  Ford Fiesta Rally3     33  31  27  34  32
52  Pellier  Laurent  /  Pelamourgues  M.  Ford Fie...   36  28  31  31  24
53  Herranen  Toni  /  Lukka  Mikko  Ford Fiesta Ra...   31  33  30  28  29
54  Dominguez  Diego  /  Peñate  Rogelio  Ford Fies...   28  30  34  36  25
55  Kallio  Jesse  /  Lindberg  Jussi  Ford Fiesta ...   29  38  28  29  51
56  Kelly  Eamonn  /  Mohan  Conor  Ford Fiesta Rally3   34  34  41  33  35
57  Kohn  Filip  /  Střeska  T.  Ford Fiesta Rally3      35  43  51  51  50
58  Hernández  R.  /  Sanjuán  R.  Ford Fiesta Rally3    51  42  42  44  36
59  Rensonnet  Tom  /  Dumont  Loïc  Ford Fiesta Ra...   39  46  49  43  38
60  Blach  Roberto  /  Barreiro  Mauro  Ford Fiesta...   44  40  43  45  37
61  Anwar  Hamza  /  Din  Adnan  Ford Fiesta Rally3      41  50  46  48  46
62  García  J.  /  Cue  Daniel  Škoda Fabia Rally2 Evo   43  39  50  50  49
63  Yamamoto  Yuki  /  Teiskonen  Miika  Renault Cl...   48  44  39  42  42
64  Otake  Nao  /  Salminen  Marko  Renault Clio Ra...   49  45  37  40  43
65  Kogure  Hikaru  /  Luhtinen  Topi  Renault Clio...   47  48  44  46  47
66  Fontana  Matteo  /  Arnaboldi  A.  Peugeot 208 ...   50  41  40  41  40
69  Rovanperä  K.  /  Halttunen  Jonne  Toyota GR Y...    1   8   1   2   9

0
ss                                                      6   7   8   9   10  11
No. Driver / Co-driver Vehicle
4   Lappi  Esapekka  /  Ferm  Janne  Hyundai i20 N ...   6   2   3   5   6   4
7   Loubet  P.  /  Gilsoul  Nicolas  Ford Puma Rall...   7   7  20   8   8   8
8   Tänak  Ott  /  Järveoja  M.  Ford Puma Rally1 H...   3   1   2   6   4   3
11  Neuville  T.  /  Wydaeghe  M.  Hyundai i20 N Ra...   5   5   4   1   3   2
18  Katsuta  T.  /  Johnston  Aaron  Toyota GR Yari...  47  45  44   7   7   5
20  Solberg  Oliver  /  Edmondson  E.  Škoda Fabia ...  11   9   7   9  12  11
21  Veiby  O.  /  Eriksen  T.  Volkswagen Polo Gti R5    9  13  10  10   9   9
22  Lindholm  Emil  /  Hämäläinen  R.  Škoda Fabia ...  14  10  12  16  11  20
23  Suninen  Teemu  /  Markkula  Mikko  Hyundai i20...  12  12   8  14  13  14
24  Huttunen  Jari  /  Linnaketo  Antti  Škoda Fabi...  16  16  10  12  17  12
25  Linnamäe  Georg  /  Morgan  James  Hyundai i20 ...  18  15  17  18  18  16
26  Kaur  Egon  /  Viilo  Jakko  Škoda Fabia Rally2...  44  14   9  15  10  17
27  Gryazin  Nikolay  /  Aleksandrov  K.  Škoda Fab...  13  17  21  20  14  14
28  Pajari  Sami  /  Mälkönen  Enni  Škoda Fabia RS...   8   8  16  13  23  13
29  Virves  Robert  /  Magalhães  Hugo  Ford Fiesta...  19  21  19  22  19  18
30  Joona  Lauri  /  Shemeikka  T.  Škoda Fabia Ral...  10  18  14  21  20  19
31  Bulacia  Marco  /  Vallejo  Diego  Škoda Fabia ...  14  20  12  16  16  22
32  Bulacia  Bruno  /  Coronado  Axel  Škoda Fabia ...  17  22  15  18  21  21
33  Evans  Elfyn  /  Martin  Scott  Toyota GR Yaris...   2   4   5   4   5   6
34  Zaldivar  F.  /  Der Ohannesian  M.  Hyundai i2...  20  19  18  42  22  23
35  Al-Rashed  Rakan  /  Moscatt  Dale  Škoda Fabia...  24  25  45  32  31  27
36  Sołowow  M.  /  Baran  Maciej  Škoda Fabia RS R...  22  24  28  24  24  24
37  Bertelli  L.  /  Scattolin  S.  Toyota GR Yaris...  43  11  39  11  15  10
38  Miele  Mauro  /  Beltrame  Luca  Škoda Fabia Ra...  29  32  42  36  38  36
40  Alonso  Daniel  /  Lopez  Alejandro  Citroën C3...  30  34  41  49  37  38
41  Jonasson  J.  /  Jonasson  N.  Škoda Fabia Rall...  21  23  22  23  51  51
42  Breen  Craig  /  Fulton  James  Hyundai i20 N R...   1   3   6   3   1   7
44  Cobbe  Luciano  /  Mometti  Roberto  Škoda Fabi...  46  44  35  51  50  49
45  Roman  Joakim  /  Lidebjer Granberg  I.  Škoda ...  40  46  45  47  47  45
46  Zaldivar  Miguel  /  Díaz  J.  Hyundai i20 N Ra...  33  35  25  34  33  33
47  Díaz Aboitiz  M.  /  Del Barrio  R.  Škoda Fabi...  45  43  43  48  49  50
48  Villanueva  A.  /  Murado  José  Škoda Fabia Ra...  26  26  31  26  32  34
49  Korhonen  Roope  /  Viinikka  Anssi  Ford Fiest...  23  31  27  25  29  25
50  Creighton  W.  /  Regan  Liam  Ford Fiesta Rally3   25  28  23  30  27  26
51  Munster  G.  /  Louka  Louis  Ford Fiesta Rally3    26  29  30  27  25  29
52  Pellier  Laurent  /  Pelamourgues  M.  Ford Fie...  28  27  29  28  28  30
53  Herranen  Toni  /  Lukka  Mikko  Ford Fiesta Ra...  49  49  49  29  26  28
54  Dominguez  Diego  /  Peñate  Rogelio  Ford Fies...  31  33  24  33  34  32
55  Kallio  Jesse  /  Lindberg  Jussi  Ford Fiesta ...  32  30  26  31  30  31
56  Kelly  Eamonn  /  Mohan  Conor  Ford Fiesta Rally3  51  48  47  37  35  37
57  Kohn  Filip  /  Střeska  T.  Ford Fiesta Rally3     49  49  49  35  36  39
58  Hernández  R.  /  Sanjuán  R.  Ford Fiesta Rally3   35  36  33  40  39  35
59  Rensonnet  Tom  /  Dumont  Loïc  Ford Fiesta Ra...  34  37  32  41  44  40
60  Blach  Roberto  /  Barreiro  Mauro  Ford Fiesta...  38  40  34  38  40  43
61  Anwar  Hamza  /  Din  Adnan  Ford Fiesta Rally3     42  42  40  50  48  48
62  García  J.  /  Cue  Daniel  Škoda Fabia Rally2 Evo  48  47  48  44  46  47
63  Yamamoto  Yuki  /  Teiskonen  Miika  Renault Cl...  39  38  36  43  42  42
64  Otake  Nao  /  Salminen  Marko  Renault Clio Ra...  36  39  36  39  41  46
65  Kogure  Hikaru  /  Luhtinen  Topi  Renault Clio...  41  41  38  46  43  44
66  Fontana  Matteo  /  Arnaboldi  A.  Peugeot 208 ...  37  51  51  45  45  41
69  Rovanperä  K.  /  Halttunen  Jonne  Toyota GR Y...   4   6   1   2   2   1

In [11]:
sweden2023_temp2 = sweden2023_temp[sweden2023_temp['No.']<30]
sweden2023_view2 = sweden2023_temp2.set_index(['No.','Driver / Co-driver Vehicle','ss'], drop=True).unstack('ss')
sweden2023_view2

0                                                      Pos.                  \
ss                                                       1   2   3   4   5
No. Driver / Co-driver Vehicle
4   Lappi  Esapekka  /  Ferm  Janne  Hyundai i20 N ...    4   3   2   5   3
7   Loubet  P.  /  Gilsoul  Nicolas  Ford Puma Rall...    8   7   8   8   2
8   Tänak  Ott  /  Järveoja  M.  Ford Puma Rally1 H...    2   2   4   3   4
11  Neuville  T.  /  Wydaeghe  M.  Hyundai i20 N Ra...    5   5   6   7   6
18  Katsuta  T.  /  Johnston  Aaron  Toyota GR Yari...    6   4   3   1  21
20  Solberg  Oliver  /  Edmondson  E.  Škoda Fabia ...   11  13   9  11   7
21  Veiby  O.  /  Eriksen  T.  Volkswagen Polo Gti R5    10  14  11  17  19
22  Lindholm  Emil  /  Hämäläinen  R.  Škoda Fabia ...   12   9  48  16   8
23  Suninen  Teemu  /  Markkula  Mikko  Hyundai i20...   14  10  13  13  45
24  Huttunen  Jari  /  Linnaketo  Antti  Škoda Fabi...    9  12  15  15  13
25  Linnamäe  Georg  /  Morgan  James  Hyundai i20 ...   22  21  20  19  17
26  Kaur  Egon  /  Viilo  Jakko  Škoda Fabia Rally2...   20  17  17  12  34
27  Gryazin  Nikolay  /  Aleksandrov  K.  Škoda Fab...   15  18  12  14  14
28  Pajari  Sami  /  Mälkönen  Enni  Škoda Fabia RS...   12  11  16  10  12
29  Virves  Robert  /  Magalhães  Hugo  Ford Fiesta...   23  20  21  20  11

0
ss                                                      6   7   8   9   10  11
No. Driver / Co-driver Vehicle
4   Lappi  Esapekka  /  Ferm  Janne  Hyundai i20 N ...   6   2   3   5   6   4
7   Loubet  P.  /  Gilsoul  Nicolas  Ford Puma Rall...   7   7  20   8   8   8
8   Tänak  Ott  /  Järveoja  M.  Ford Puma Rally1 H...   3   1   2   6   4   3
11  Neuville  T.  /  Wydaeghe  M.  Hyundai i20 N Ra...   5   5   4   1   3   2
18  Katsuta  T.  /  Johnston  Aaron  Toyota GR Yari...  47  45  44   7   7   5
20  Solberg  Oliver  /  Edmondson  E.  Škoda Fabia ...  11   9   7   9  12  11
21  Veiby  O.  /  Eriksen  T.  Volkswagen Polo Gti R5    9  13  10  10   9   9
22  Lindholm  Emil  /  Hämäläinen  R.  Škoda Fabia ...  14  10  12  16  11  20
23  Suninen  Teemu  /  Markkula  Mikko  Hyundai i20...  12  12   8  14  13  14
24  Huttunen  Jari  /  Linnaketo  Antti  Škoda Fabi...  16  16  10  12  17  12
25  Linnamäe  Georg  /  Morgan  James  Hyundai i20 ...  18  15  17  18  18  16
26  Kaur  Egon  /  Viilo  Jakko  Škoda Fabia Rally2...  44  14   9  15  10  17
27  Gryazin  Nikolay  /  Aleksandrov  K.  Škoda Fab...  13  17  21  20  14  14
28  Pajari  Sami  /  Mälkönen  Enni  Škoda Fabia RS...   8   8  16  13  23  13
29  Virves  Robert  /  Magalhães  Hugo  Ford Fiesta...  19  21  19  22  19  18